### PR TITLE
Continuing work from #248

### PR DESCRIPTION
**Pull request by taigrr**
Commits and rebasing made things a bit messy and GH auto-closed the PR. I'm reopening it here. (ref: #248)

### CODE REVIEW

**Comment by taigrr** [comment]
@andydotxyz this looks to still be requiring 1.14 in the tests even after merging in the changes.

**Comment by andydotxyz** [comment]
Apologies, I have fixed the settings now

**Comment by andydotxyz** [comment]
This looks good - can you do a sanity check for file size before and after, just to make sure it's still happy. I don't think there are lots of big files here but good to know.

**Comment by taigrr** [comment]
File size of the built fynedesk executable you mean?

**Review by andydotxyz — APPROVED** [review]
Thanks :)

**Pull request merged**
